unit fpdev.fpc.activator;

{$mode objfpc}{$H+}

{
  FPC Activator
  
  This module handles FPC version activation for different scopes.
  It creates activation scripts and updates IDE settings.
  Uses dependency injection for testability.
  
  NOTE: All shared types are in fpdev.fpc.types.pas
  NOTE: Uses fpdev.fpc.utils for FindProjectRoot
}

interface

uses
  SysUtils, Classes, fpjson, jsonparser, fpdev.config.interfaces, fpdev.types, fpdev.fpc.types,
  fpdev.fpc.version, fpdev.fpc.interfaces, fpdev.fpc.utils;

type
  { TFPCActivator - Handles FPC version activation }
  TFPCActivator = class
  private
    FVersionManager: TFPCVersionManager;
    FConfigManager: IConfigManager;
    FFileSystem: IFileSystem;
    FOwnsInterfaces: Boolean;

    function CreateWindowsActivationScript(const AScriptPath, ABinPath: string): Boolean;
    function CreateUnixActivationScript(const AScriptPath, ABinPath: string): Boolean;
    function UpdateVSCodeSettings(const AProjectRoot, ABinPath: string): Boolean;
    function ActivateProjectScope(const AVersion, ABinPath: string; var AResult: TActivationResult): Boolean;
    function ActivateUserScope(const AVersion, ABinPath: string; var AResult: TActivationResult): Boolean;

  public
    { Creates a new activator with default file system. }
    constructor Create(AVersionManager: TFPCVersionManager; AConfigManager: IConfigManager); overload;

    { Creates a new activator with custom dependencies for testing. }
    constructor Create(AVersionManager: TFPCVersionManager; AConfigManager: IConfigManager;
      AFileSystem: IFileSystem); overload;
    destructor Destroy; override;

    { Activates a specific FPC version for the current scope. }
    function ActivateVersion(const AVersion: string): TActivationResult;

    property VersionManager: TFPCVersionManager read FVersionManager;
    property ConfigManager: IConfigManager read FConfigManager;
    property FileSystem: IFileSystem read FFileSystem;
  end;

implementation

uses fpdev.fpc.defaults;

{ TFPCActivator }

constructor TFPCActivator.Create(AVersionManager: TFPCVersionManager; AConfigManager: IConfigManager);
begin
  inherited Create;
  FVersionManager := AVersionManager;
  FConfigManager := AConfigManager;
  FFileSystem := TDefaultFileSystem.Create;
  FOwnsInterfaces := True;
end;

constructor TFPCActivator.Create(AVersionManager: TFPCVersionManager; AConfigManager: IConfigManager;
  AFileSystem: IFileSystem);
begin
  inherited Create;
  FVersionManager := AVersionManager;
  FConfigManager := AConfigManager;
  FFileSystem := AFileSystem;
  FOwnsInterfaces := False;
end;

destructor TFPCActivator.Destroy;
begin
  FFileSystem := nil;
  inherited Destroy;
end;

function TFPCActivator.CreateWindowsActivationScript(const AScriptPath, ABinPath: string): Boolean;
var
  Script: TStringList;
begin
  Result := False;
  try
    Script := TStringList.Create;
    try
      Script.Add('@echo off');
      Script.Add('REM FPC Environment Activation Script');
      Script.Add('REM Generated by fpdev');
      Script.Add('');
      Script.Add('SET "PATH=' + ABinPath + ';%PATH%"');
      Script.Add('');
      Script.Add('echo FPC environment activated');
      Script.Add('echo FPC bin directory: ' + ABinPath);

      FFileSystem.WriteTextFile(AScriptPath, Script.Text);
      Result := True;
    finally
      Script.Free;
    end;
  except
    Result := False;
  end;
end;

function TFPCActivator.CreateUnixActivationScript(const AScriptPath, ABinPath: string): Boolean;
var
  Script: TStringList;
begin
  Result := False;
  try
    Script := TStringList.Create;
    try
      Script.Add('#!/bin/sh');
      Script.Add('# FPC Environment Activation Script');
      Script.Add('# Generated by fpdev');
      Script.Add('');
      Script.Add('export PATH="' + ABinPath + ':$PATH"');
      Script.Add('');
      Script.Add('echo "FPC environment activated"');
      Script.Add('echo "FPC bin directory: ' + ABinPath + '"');

      FFileSystem.WriteTextFile(AScriptPath, Script.Text);
      Result := True;
    finally
      Script.Free;
    end;
  except
    Result := False;
  end;
end;

function TFPCActivator.UpdateVSCodeSettings(const AProjectRoot, ABinPath: string): Boolean;
var
  VSCodeDir, SettingsPath, JSONText: string;
  JSON: TJSONObject;
  Parser: TJSONParser;
  EnvObj: TJSONObject;
  PathValue: string;
begin
  Result := False;
  try
    VSCodeDir := AProjectRoot + PathDelim + '.vscode';
    if not FFileSystem.DirectoryExists(VSCodeDir) then
      FFileSystem.ForceDirectories(VSCodeDir);

    SettingsPath := VSCodeDir + PathDelim + 'settings.json';

    if FFileSystem.FileExists(SettingsPath) then
    begin
      JSONText := FFileSystem.ReadTextFile(SettingsPath);
      if JSONText <> '' then
      begin
        Parser := TJSONParser.Create(JSONText);
        try
          JSON := TJSONObject(Parser.Parse);
        finally
          Parser.Free;
        end;
      end
      else
        JSON := TJSONObject.Create;
    end
    else
      JSON := TJSONObject.Create;

    try
      {$IFDEF MSWINDOWS}
      if not JSON.Find('terminal.integrated.env.windows', EnvObj) then
      begin
        EnvObj := TJSONObject.Create;
        JSON.Add('terminal.integrated.env.windows', EnvObj);
      end;
      PathValue := ABinPath + ';%PATH%';
      {$ENDIF}

      {$IFDEF LINUX}
      if not JSON.Find('terminal.integrated.env.linux', EnvObj) then
      begin
        EnvObj := TJSONObject.Create;
        JSON.Add('terminal.integrated.env.linux', EnvObj);
      end;
      PathValue := ABinPath + ':$PATH';
      {$ENDIF}

      {$IFDEF DARWIN}
      if not JSON.Find('terminal.integrated.env.osx', EnvObj) then
      begin
        EnvObj := TJSONObject.Create;
        JSON.Add('terminal.integrated.env.osx', EnvObj);
      end;
      PathValue := ABinPath + ':$PATH';
      {$ENDIF}

      EnvObj.Strings['PATH'] := PathValue;
      FFileSystem.WriteTextFile(SettingsPath, JSON.FormatJSON);
      Result := True;
    finally
      JSON.Free;
    end;
  except
    Result := False;
  end;
end;

function TFPCActivator.ActivateProjectScope(const AVersion, ABinPath: string; var AResult: TActivationResult): Boolean;
var
  ProjectRoot, EnvDir: string;
  ActivateCmd, ActivateSh, VSCodeSettingsPath: string;
begin
  Result := False;

  ProjectRoot := fpdev.fpc.utils.FindProjectRoot(GetCurrentDir);
  if ProjectRoot = '' then
  begin
    AResult.ErrorMessage := 'Cannot find project root (.fpdev directory)';
    Exit;
  end;

  EnvDir := ProjectRoot + PathDelim + '.fpdev' + PathDelim + 'env';
  if not FFileSystem.DirectoryExists(EnvDir) then
    FFileSystem.ForceDirectories(EnvDir);

  ActivateCmd := EnvDir + PathDelim + 'activate.cmd';
  ActivateSh := EnvDir + PathDelim + 'activate.sh';

  if not CreateWindowsActivationScript(ActivateCmd, ABinPath) then
  begin
    AResult.ErrorMessage := 'Failed to create Windows activation script';
    Exit;
  end;

  if not CreateUnixActivationScript(ActivateSh, ABinPath) then
  begin
    AResult.ErrorMessage := 'Failed to create Unix activation script';
    Exit;
  end;

  AResult.ActivationScript := ActivateCmd;

  if UpdateVSCodeSettings(ProjectRoot, ABinPath) then
  begin
    VSCodeSettingsPath := ProjectRoot + PathDelim + '.vscode' + PathDelim + 'settings.json';
    AResult.VSCodeSettings := VSCodeSettingsPath;
  end;

  {$IFDEF MSWINDOWS}
  AResult.ShellCommand := '.fpdev\env\activate.cmd';
  {$ELSE}
  AResult.ShellCommand := 'source .fpdev/env/activate.sh';
  {$ENDIF}

  Result := True;
end;

function TFPCActivator.ActivateUserScope(const AVersion, ABinPath: string; var AResult: TActivationResult): Boolean;
var
  EnvDir: string;
  ActivateCmd, ActivateSh: string;
begin
  Result := False;

  EnvDir := ExtractFileDir(FConfigManager.GetConfigPath) + PathDelim + 'env';
  if not FFileSystem.DirectoryExists(EnvDir) then
    FFileSystem.ForceDirectories(EnvDir);

  ActivateCmd := EnvDir + PathDelim + 'activate-' + AVersion + '.cmd';
  ActivateSh := EnvDir + PathDelim + 'activate-' + AVersion + '.sh';

  if not CreateWindowsActivationScript(ActivateCmd, ABinPath) then
  begin
    AResult.ErrorMessage := 'Failed to create Windows activation script';
    Exit;
  end;

  if not CreateUnixActivationScript(ActivateSh, ABinPath) then
  begin
    AResult.ErrorMessage := 'Failed to create Unix activation script';
    Exit;
  end;

  AResult.ActivationScript := ActivateCmd;

  {$IFDEF MSWINDOWS}
  AResult.ShellCommand := EnvDir + PathDelim + 'activate-' + AVersion + '.cmd';
  {$ELSE}
  AResult.ShellCommand := 'source ' + EnvDir + PathDelim + 'activate-' + AVersion + '.sh';
  {$ENDIF}

  Result := True;
end;

function TFPCActivator.ActivateVersion(const AVersion: string): TActivationResult;
var
  Scope: fpdev.types.TInstallScope;
  InstallPath, BinPath: string;
begin
  FillChar(Result, SizeOf(Result), 0);
  Result.Success := False;

  if not FVersionManager.IsVersionInstalled(AVersion) then
  begin
    Result.ErrorMessage := 'FPC version ' + AVersion + ' is not installed';
    Exit;
  end;

  InstallPath := FVersionManager.GetVersionInstallPath(AVersion);
  BinPath := InstallPath + PathDelim + 'bin';

  Scope := DetectInstallScope(GetCurrentDir);
  Result.Scope := Scope;

  if Scope = fpdev.types.isProject then
  begin
    if not ActivateProjectScope(AVersion, BinPath, Result) then
      Exit;
  end
  else
  begin
    if not ActivateUserScope(AVersion, BinPath, Result) then
      Exit;
  end;

  if not FConfigManager.GetToolchainManager.SetDefaultToolchain('fpc-' + AVersion) then
  begin
    Result.ErrorMessage := 'Failed to set default version';
    Exit;
  end;

  Result.Success := True;
end;

end.
